
version: 2.1
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: build_and_push_image
          command: docker build -t travis-ci.test .
      - run:
          name: run_tests_chrome
          command: docker run --env BROWSER=chrome -it ashot90docker/myimage:latest
      - run:
          name: run_tests_ff
          command: docker run --env BROWSER=firefox -it ashot90docker/myimage:latest
