version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: |
         if [ "${CIRCLE_BRANCH}" == "docker_image_update" ]; then
            echo ash1990@hd | docker login -u ashot90docker --password-stdin &&
            docker build -t ashot90docker/myimage:latest . &&
            docker push ashot90docker/myimage:latest
         fi
      - run:
          name: pull_image
          command: docker pull ashot90docker/myimage:latest
      - run:
          name: run_tests_chrome
          command: docker run --env BROWSER=chrome -it ashot90docker/myimage:latest
      - run:
          name: run_tests_ff
          command: docker run --env BROWSER=firefox -it ashot90docker/myimage:latest
