version: 2.1
jobs:
  build:
    steps:
      - checkout
      - run:
          name: build_image
          command: docker build -t travis-ci.test .
      - run:
          name: run_tests_chrome
          command: docker run --env BROWSER=chrome -it travis-ci.test
      - run:
          name: run_tests_ff
          command: docker run --env BROWSER=firefox -it travis-ci.test

