version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: |
         if [ "${CIRCLE_BRANCH}" == "docker_image_update" ]; then
            echo $DOCKER_HUB_PSW | docker login -u $DOCKER_HUB_USER --password-stdin
            docker build -t ashot90docker/myimage:latest . 
            docker push ashot90docker/myimage:latest
         fi
      - run:
          name: pull_image
          command: docker pull ashot90docker/myimage:latest
      - run:
          name: run_tests_chrome
          command: docker run --env BROWSER=chrome -it ashot90docker/myimage:latest
      - run:
          name: run_tests_ff
          command: docker run --env BROWSER=firefox -it ashot90docker/myimage:latest
