
version: 2.1
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: build_image
          command: docker build -t circle-ci.test .
      - run:
          name: run_tests_chrome
          command: docker run --env BROWSER=chrome -it circle-ci.test
      - run:
          name: run_tests_ff
          command: docker run --env BROWSER=firefox -it circle-ci.test
